#!/bin/sh
[% c("var/set_default_env") -%]
distdir=/var/tmp/dist/StemNS
mkdir /var/tmp/build
mkdir /var/tmp/dist

# Extract StemNS
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz

cp -a /var/tmp/build/[% project %]-[% c('version') %] ${distdir}

cd /var/tmp/dist/

[% c('tar', {
        tar_src => '.',
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
