#!/bin/bash
[% c("var/set_default_env") -%]
[% pc('python', 'var/setup', { python_tarfile => c('input_files_by_name/python') }) %]

tar xvf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]

python3 setup.py sdist --format=gztar

mkdir -p /var/tmp/build/sdist/[% project %]
tar -C /var/tmp/build/sdist/[% project %] -xvf dist/QDarkStyle-[% c('version') %].tar.gz

mkdir -p /var/tmp/dist/[% project %]
cd /var/tmp/dist/[% project %]

mkdir ./[% project %]
cp -a /var/tmp/build/sdist/[% project %]/QDarkStyle*/[% project %]/*.py ./[% project %]/

[% c('tar', {
        tar_src => '.',
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
