#!/bin/bash
[% c("var/set_default_env") -%]
tar xvf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]
[% c('zip', {
        zip_src => [ '.' ],
        zip_args => dest_dir _ '/' _ c('filename'),
    }) %]
