#!/bin/bash
[% c("var/set_default_env") -%]
[% pc('go', 'var/setup', { go_tarfile => c('input_files_by_name/go') }) %]
export CGO_ENABLED=[% c("var/cgo") %]
distdir=/var/tmp/dist/[% project %]
mkdir -p $distdir

[% FOREACH dep = c("var/go_lib_deps") -%]
  tar -C /var/tmp/dist -xf [% c('input_files_by_name/' _ dep) %]
[% END -%]

mkdir -p $GOPATH/src/github.com/coredns
tar -C $GOPATH/src/github.com/coredns -xf [% project %]-[% c('version') %].tar.gz
mv $GOPATH/src/github.com/coredns/coredns-utils-[% c('version') %] $GOPATH/src/github.com/coredns/coredns-utils

# TODO: Remove static build ID after migrating to Go 1.13.3+
go install $TAGS -ldflags '-s -buildid=' github.com/coredns/coredns-utils/coredns-keygen

[% IF c("var/linux-x86_64") -%]
  GOPATHBIN="${GOPATH}/bin"
[% ELSE -%]
  GOPATHBIN="${GOPATH}/bin/${GOOS}_${GOARCH}"
[% END -%]

cd /var/tmp/dist

# Build as executable

cp -a $GOPATHBIN/coredns-keygen[% IF c("var/windows") %].exe[% END %] $distdir/

cd $distdir
[% c('tar', {
   tar_src   => [ '.' ],
   tar_args  => '-czf ' _ dest_dir _ '/' _ c('filename'),
  }) %]
