#!/bin/bash
[% c("var/set_default_env") -%]
[% pc('python', 'var/setup', { python_tarfile => c('input_files_by_name/python') }) %]

shopt -s globstar

unzip dnspython-[% c('version') %].zip
cd dnspython-[% c('version') %]

python3 setup.py sdist --format=gztar

mkdir -p /var/tmp/build/sdist/[% project %]
tar -C /var/tmp/build/sdist/[% project %] -xvf dist/dnspython-[% c('version') %].tar.gz

mkdir -p /var/tmp/dist/[% project %]
cd /var/tmp/dist/[% project %]

mkdir ./[% project %]
cd /var/tmp/build/sdist/[% project %]/dnspython*/[% project %]
cp --parents **/*.py /var/tmp/dist/[% project %]/[% project %]/

cd /var/tmp/dist/[% project %]
[% c('tar', {
        tar_src => '.',
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
