#!/bin/bash
[% c("var/set_default_env") -%]
[% pc('python', 'var/setup', { python_tarfile => c('input_files_by_name/python') }) %]

tar xvf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]

python3 setup.py sdist --format=gztar

mkdir -p /var/tmp/build/sdist/[% project %]
tar -C /var/tmp/build/sdist/[% project %] -xvf dist/[% project %]-[% c('version') %].tar.gz

mkdir -p /var/tmp/dist/[% project %]
cd /var/tmp/dist/[% project %]

cp -a /var/tmp/build/sdist/[% project %]/[% project %]*/[% project %] ./[% project %]

[% IF c("var/only_top_10_issuers") %]
  cp $rootdir/roots_of_top_10_issuers.pem ./[% project %]/cacert.pem
[% END %]

[% c('tar', {
        tar_src => '.',
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
