#!/bin/bash
[% c("var/set_default_env") -%]

distdir=/var/tmp/dist/[% project %]
mkdir -p $distdir

tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/ncdns') %]
tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/ncp11') %]
tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/ncprop279') %]
tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/q') %]

cd $distdir
[% c('tar', {
   tar_src   => [ '.' ],
   tar_args  => '-cJf ' _ dest_dir _ '/' _ c('filename'),
 }) %]
