#!/bin/bash
[% c("var/set_default_env") -%]

distdir=/var/tmp/dist/[% project %]
mkdir -p $distdir

[% IF c("var/windows") %]
  tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/certinject') %]
[% END %]
tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/encaya') %]
tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/generate_nmc_cert') %]
tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/ncdns') %]
[% IF ! c("var/osx") %]
  tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/ncp11') %]
[% END %]
tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/ncprop279') %]
tar -C /var/tmp/dist/[% project %] -xf [% c('input_files_by_name/q') %]

cd $distdir
[% c('tar', {
   tar_src   => [ '.' ],
   tar_args  => '-cJf ' _ dest_dir _ '/' _ c('filename'),
 }) %]
