#!/bin/sh
[% c("var/set_default_env") -%]
distdir=/var/tmp/dist/[% project %]
mkdir /var/tmp/build
tar -C /var/tmp/build -xf Electrum-NMC-[% c("version") %].tar.gz
cd /var/tmp/build/Electrum-NMC-[% c("version") %]

cd /var/tmp/build/
[% c('tar', {
        tar_src => 'Electrum-NMC-' _ c("version"),
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
